# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "67a8f61ca9ad53a07e0f732ba385700b"
name = "lingotuner-translate-app"
application_url = "https://lingotuner.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

# Mandatory compliance webhooks (App Store)
# https://shopify.dev/docs/apps/build/compliance/privacy-law-compliance
[[webhooks.subscriptions]]
uri = "/webhooks/customers/data_request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers/redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "/webhooks/shop/redact"
compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locales,read_translations,write_translations"

[auth]
redirect_urls = [
  "https://lingotuner.vercel.app/auth/callback",
  "https://lingotuner.vercel.app/auth/shopify/callback"
]
